"""Refactor3

Revision ID: 12146fadedd7
Revises: 207db1a15f00
Create Date: 2023-09-23 16:55:05.384903

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '12146fadedd7'
down_revision = '207db1a15f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('donation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donation', type_='foreignkey')
    op.drop_column('donation', 'user_id')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
