"""Refactor2

Revision ID: 207db1a15f00
Revises: 42edb3c2221c
Create Date: 2023-09-23 16:24:33.072337

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '207db1a15f00'
down_revision = '42edb3c2221c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
