"""Added Donation

Revision ID: 42edb3c2221c
Revises: a2eaff9cf870
Create Date: 2023-09-23 16:19:53.832060

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '42edb3c2221c'
down_revision = 'a2eaff9cf870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=False),
    sa.Column('fully_invested', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
